INSERT INTO categories (id, icono, name) VALUES (1, 'ios-basket', 'ABARROTES');
INSERT INTO categories (id, icono, name) VALUES (2, 'ios-pizza', 'CONGELADOS');
INSERT INTO categories (id, icono, name) VALUES (3, 'ios-cart', 'GOLOSINAS');
INSERT INTO categories (id, icono, name) VALUES (4, 'ios-cafe', 'LACTEOS');
INSERT INTO categories (id, icono, name) VALUES (5, 'ios-archive', 'PAN');
INSERT INTO categories (id, icono, name) VALUES (6, 'ios-flask', 'LIMPIEZA Y OTROS');
INSERT INTO categories (id, icono, name) VALUES (7, 'ios-color-fill', 'BEBIDAS');
INSERT INTO categories (id, icono, name) VALUES (8, 'ios-color-fill', 'FIAMBRERIA');
INSERT INTO categories (id, icono, name) VALUES (11, 'ios-color-fill', 'FRUTAS Y VERDURAS');
INSERT INTO categories (id, icono, name) VALUES (12, 'ios-flask', 'POSTRES');
INSERT INTO categories (id, icono, name) VALUES (13, 'ios-flask', 'PREPARADOS');
INSERT INTO categories (id, icono, name) VALUES (14, 'ios-color-fill', 'PROMOCIONES');
INSERT INTO categories (id, icono, name) VALUES (15, 'ios-color-fill', 'SERVICIOS');